prompts = [
    "Generate code for a complex geometric flower pattern using nested loops.",
    "Draw a starburst shape where the line width changes randomly.",
    "Create a fractal-like pattern using recursion or repeating functions.",
    "Draw a spiraling pattern of squares with random colors for each side.",
    "Generate a simple, symmetric pattern of concentric circles.",
    "Make a modern art design with many lines drawn at random angles and lengths.",
    "Draw a single square with a side length of 100.",
    "Create a Lissajous curve by calculating the sine and cosine coordinates for a wide range of angles and using t.goto(). The curve must be drawn with a thin line.",
    "Draw a starburst pattern consisting of 36 lines radiating from the center, where the length of each line is determined by a random number between 50 and 200, and the color of each line is randomly selected from a list of five predefined vivid colors.",
    "Write a function called draw_polygon(sides, size) and use it within a nested loop to draw 10 different polygons, increasing the number of sides and decreasing the size slightly for each repetition.",
    "Generate a spirograph using mathematical formulas to calculate the coordinates, ensuring the result fills a large portion of the canvas.",
    "Draw a sequence of capital letters  using custom turtle movements for each character, ensuring they are evenly spaced.",
     "Create a sunset scene by drawing a large circle that touches the bottom of the canvas, filling it with a radial color gradient (using many thin lines or stamping shapes with changing colors)."
    "Draw a hyperbolic spiral (or reciprocal spiral) where the distance from the center decreases inversely with the angle, using t.setheading() and t.forward().",
    "Create a woven basket texture pattern by drawing overlapping horizontal and vertical lines and slightly changing the color/line thickness where they intersect to simulate depth.",
    "Draw a rainbow arc using 7 distinct colors where the line thickness for each color is constant, and the arcs are concentric.",
    "draw a face",
    "Implement a cellular automaton like Rule 30 or the simpler Rule 90. The turtle should draw the pattern row by row based on the state of the cells in the previous row",
    "Simulate a random walk (drunkard's walk): the turtle takes 20 steps, where the distance of each step is constant, but the turning angle is chosen randomly between -90 and 90 degrees.",
    "Draw a circular spiral that changes color based on its distance from the center. The colors should cycle smoothly through the RGB spectrum as the spiral expands.",
    "Draw a star polygon (or stellate polygon) by connecting every nth vertex of a regular m-sided polygon",
    "Draw a stylized lightning bolt pattern using random offsets to simulate the jagged, branching nature of a strike",
    "Create a Kock snowflake **(or Koch curve on a single line) fractal, drawing the pattern up to the 3rd iteration.",
    "Draw a dog",
    "Draw a checkerboard pattern using two random alternating colors",
    "Draw a sequence of 10 circles where the radius of each subsequent circle is determined by the Fibonacci sequence (1, 1, 2, 3, 5, 8, ...).",    
]
    